import Foundation
import CoreVideo

/// CPU painter for the spike's test patterns. It is deliberately simple: SMPTE-style colour bars in the
/// upper two thirds, a solid band in the lower third whose colour tells the tester which side produced
/// the frame, a moving square, and a progress line that grows by one pixel per frame so dropped or
/// duplicated frames are visible in a recording.
///
/// Blue band = frames generated by the host app and delivered through the sink stream.
/// Red band  = fallback frames generated inside the extension (host absent or stalled).
struct TestPatternPainter {
    enum Style {
        case hostFrame
        case extensionFallback
    }

    let width: Int
    let height: Int
    private let barRow: [UInt8]

    init(width: Int, height: Int) {
        self.width = width
        self.height = height
        // BGRA colour bars: white, yellow, cyan, green, magenta, red, blue, black.
        let colors: [(UInt8, UInt8, UInt8)] = [
            (235, 235, 235), (16, 235, 235), (235, 235, 16), (16, 235, 16),
            (235, 16, 235), (16, 16, 235), (235, 16, 16), (16, 16, 16),
        ]
        var row = [UInt8](repeating: 255, count: width * 4)
        for x in 0..<width {
            let c = colors[min(colors.count - 1, x * colors.count / max(1, width))]
            row[x * 4] = c.0
            row[x * 4 + 1] = c.1
            row[x * 4 + 2] = c.2
            row[x * 4 + 3] = 255
        }
        barRow = row
    }

    func paint(into pixelBuffer: CVPixelBuffer, frameIndex: Int, style: Style) {
        CVPixelBufferLockBaseAddress(pixelBuffer, [])
        defer { CVPixelBufferUnlockBaseAddress(pixelBuffer, []) }
        guard let base = CVPixelBufferGetBaseAddress(pixelBuffer) else { return }
        let bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer)
        let bufferWidth = min(width, CVPixelBufferGetWidth(pixelBuffer))
        let bufferHeight = min(height, CVPixelBufferGetHeight(pixelBuffer))
        let rowBytes = bufferWidth * 4
        let barsEnd = bufferHeight * 2 / 3

        let band: (UInt8, UInt8, UInt8)
        switch style {
        case .hostFrame: band = (160, 64, 24)          // BGRA: blue
        case .extensionFallback: band = (24, 24, 150)  // BGRA: red
        }

        barRow.withUnsafeBufferPointer { bars in
            for y in 0..<bufferHeight {
                let row = base.advanced(by: y * bytesPerRow).assumingMemoryBound(to: UInt8.self)
                if y < barsEnd {
                    memcpy(row, bars.baseAddress!, rowBytes)
                } else {
                    var x = 0
                    while x < bufferWidth {
                        row[x * 4] = band.0
                        row[x * 4 + 1] = band.1
                        row[x * 4 + 2] = band.2
                        row[x * 4 + 3] = 255
                        x += 1
                    }
                }
            }
        }

        // Moving square: sweeps across the lower band once every ~9 seconds at 30 fps.
        let square = max(8, bufferHeight / 12)
        let travel = max(1, bufferWidth - square)
        let sx = (frameIndex * 7) % travel
        let sy = barsEnd + (bufferHeight - barsEnd - square) / 2
        for y in sy..<min(bufferHeight, sy + square) {
            let row = base.advanced(by: y * bytesPerRow).assumingMemoryBound(to: UInt8.self)
            for x in sx..<min(bufferWidth, sx + square) {
                row[x * 4] = 255
                row[x * 4 + 1] = 255
                row[x * 4 + 2] = 255
                row[x * 4 + 3] = 255
            }
        }

        // Progress line: one pixel longer per frame, wraps every `bufferWidth` frames.
        let lineLength = frameIndex % max(1, bufferWidth)
        for y in max(0, barsEnd - 6)..<barsEnd {
            let row = base.advanced(by: y * bytesPerRow).assumingMemoryBound(to: UInt8.self)
            for x in 0..<lineLength {
                row[x * 4] = 0
                row[x * 4 + 1] = 0
                row[x * 4 + 2] = 0
                row[x * 4 + 3] = 255
            }
        }
    }
}
