using System;
using System.Collections.Generic;

namespace VRMCast.Core.Localization
{
    /// <summary>
    /// All UI strings, keyed. Both languages must define exactly the same keys (enforced by tests).
    /// Keys are grouped by screen area; "{0}" style placeholders follow string.Format.
    /// </summary>
    public static class LocalizationTable
    {
        public static IReadOnlyDictionary<string, string> For(AppLanguage language)
        {
            switch (language)
            {
                case AppLanguage.En: return English;
                default: return TraditionalChinese;
            }
        }

        public static IEnumerable<string> Keys => English.Keys;

        public static readonly IReadOnlyDictionary<string, string> TraditionalChinese = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Header / status bar
            ["header.subtitle"] = "渲染基礎（MVP-A）",
            ["header.profile"] = "設定檔：預設",
            ["header.language"] = "語言",
            ["status.face"] = "臉部：關",
            ["status.audio"] = "音訊：關",
            ["status.render"] = "渲染 {0} fps",
            ["status.outputOn"] = "輸出：開",
            ["status.outputOff"] = "輸出：關",
            ["status.resolution"] = "{0}×{1} | {2} FPS",

            // Model section
            ["section.model"] = "模型",
            ["model.none"] = "尚未載入模型",
            ["model.hint"] = "請載入 .vrm 檔案開始使用。",
            ["model.load"] = "載入 VRM",
            ["model.loading"] = "載入中…",
            ["model.unload"] = "卸載",
            ["model.status"] = "{0}{1} · {2} 個表情 · SpringBone {3}",
            ["model.author"] = " · {0}",
            ["model.springOn"] = "有",
            ["model.springOff"] = "無",
            ["model.loaded"] = "已載入 {0}",
            ["import.title"] = "進階匯入",
            ["import.version"] = "VRM 版本",
            ["import.auto"] = "自動偵測",
            ["import.force0"] = "強制 VRM 0.x",
            ["import.force1"] = "強制 VRM 1.0",
            ["import.retry"] = "以此版本重試",

            // Framing section
            ["section.framing"] = "構圖",
            ["framing.preset"] = "預設",
            ["framing.face"] = "臉部",
            ["framing.bust"] = "胸像",
            ["framing.halfBody"] = "半身",
            ["framing.fullBody"] = "全身",
            ["framing.zoom"] = "縮放",
            ["framing.fov"] = "視角",
            ["framing.resetCamera"] = "重設鏡頭",
            ["framing.resetOrientation"] = "重設方向",
            ["framing.reframe"] = "重新對準模型",
            ["framing.hint"] = "預覽區：滾輪或觸控板兩指上下滑＝縮放，拖曳＝環繞，右鍵／中鍵或 Shift＋拖曳＝平移",

            // Background section
            ["section.background"] = "背景",
            ["background.mode"] = "模式",
            ["background.solid"] = "純色",
            ["background.image"] = "圖片",
            ["background.chroma"] = "去背綠幕",
            ["background.transparent"] = "透明",
            ["background.keyColor"] = "去背色",
            ["background.color"] = "顏色",
            ["background.chooseImage"] = "選擇圖片…",
            ["background.clearImage"] = "清除",
            ["background.noImage"] = "尚未選擇圖片",
            ["background.fit"] = "填滿方式",
            ["fit.fill"] = "填滿",
            ["fit.fit"] = "等比置入",
            ["fit.stretch"] = "拉伸",
            ["background.colorFormat"] = "請以 #RRGGBB 格式輸入顏色。",

            // Output section
            ["section.output"] = "輸出",
            ["output.quality"] = "品質",
            ["output.recommended"] = "建議",
            ["output.hint"] = "「開始輸出」會把畫面送到虛擬攝影機；尚未安裝原生元件時只啟動除錯用的接收端。",
            ["vcam.title"] = "虛擬攝影機",
            ["vcam.install"] = "安裝／啟用虛擬攝影機",
            ["vcam.uninstall"] = "移除",
            ["vcam.status.unsupported"] = "狀態：此環境不支援（{0}）",
            ["vcam.status.unknown"] = "狀態：查詢中…",
            ["vcam.status.notInstalled"] = "狀態：未安裝",
            ["vcam.status.requesting"] = "狀態：向 macOS 送出請求中…",
            ["vcam.status.awaitingApproval"] = "狀態：等待核准。請到「系統設定 › 一般 › 登入項目與延伸功能 › 相機延伸功能」允許 VRMCast。",
            ["vcam.status.ready"] = "狀態：已啟用 {0}，OBS 可選擇「VRM Live Camera」。",
            ["vcam.status.enabledNoDevice"] = "狀態：已啟用 {0}，但系統尚未列出攝影機裝置，請稍候或重新開啟 OBS。",
            ["vcam.status.needsReboot"] = "狀態：已安裝，需重新啟動 macOS 才會生效。",
            ["vcam.status.failed"] = "狀態：失敗（{1}）",
            ["vcam.status.uninstalling"] = "狀態：移除中…",
            ["vcam.hint"] = "第一次安裝時 macOS 會要求你在系統設定中允許延伸功能；核准後不需要再安裝。停止輸出時攝影機會顯示備援畫面，不會凍結。",
            ["vcam.hint.notBundled"] = "此版本的 App 內未內建攝影機延伸功能。請用 Scripts/package-macos.sh 打包並簽章後再安裝。",
            ["vcam.hint.unsupported"] = "虛擬攝影機只在 macOS 上、且已編譯 VRMCastFrameBridge.bundle 時可用（Scripts/build-frame-bridge.sh）。",
            ["vcam.openFailed"] = "無法連到虛擬攝影機：{0}。請先安裝並核准延伸功能。",
            ["vcam.openFailed.generic"] = "無法啟動輸出。",
            ["output.start"] = "開始輸出",
            ["output.stop"] = "停止輸出",

            // Diagnostics section
            ["section.diagnostics"] = "診斷",
            ["diag.render"] = "渲染：{0} fps（{1} ms）",
            ["diag.output"] = "輸出：{0}×{1} @ {2} · 目標 {3}",
            ["diag.avatar"] = "模型：{0} [{1}]",
            ["diag.copy"] = "複製診斷資訊",
            ["diag.copied"] = "診斷資訊已複製到剪貼簿。",

            // File picker
            ["picker.loadVrm"] = "載入 VRM",
            ["picker.chooseImage"] = "選擇背景圖片",
            ["picker.up"] = "上一層",
            ["picker.home"] = "個人",
            ["picker.desktop"] = "桌面",
            ["picker.downloads"] = "下載項目",
            ["picker.documents"] = "文件",
            ["picker.cancel"] = "取消",
            ["picker.open"] = "開啟",
            ["picker.folderUnreadable"] = "無法讀取這個資料夾。",
            ["picker.fileMissing"] = "找不到這個檔案。",
            ["picker.wrongType"] = "這裡不支援這種檔案類型。",

            // Camera (webcam)
            ["section.camera"] = "攝影機",
            ["camera.device"] = "裝置",
            ["camera.mirror"] = "鏡像預覽",
            ["camera.none"] = "找不到攝影機",
            ["camera.state.stopped"] = "未啟動（按「開始追蹤」後啟用）",
            ["camera.state.permission"] = "正在請求攝影機權限…",
            ["camera.state.denied"] = "攝影機權限被拒絕。請到「系統設定 › 隱私權與安全性 › 攝影機」允許 VRMCast。",
            ["camera.state.starting"] = "啟動中…",
            ["camera.state.running"] = "運作中",
            ["camera.state.stalled"] = "沒有影像，正在嘗試恢復…",
            ["camera.state.noDevice"] = "找不到所選的攝影機。",
            ["camera.state.failed"] = "攝影機啟動失敗，正在重試…",

            // Tracking
            ["section.tracking"] = "追蹤",
            ["tracking.start"] = "開始追蹤",
            ["tracking.stop"] = "停止追蹤",
            ["tracking.calibrate"] = "校正",
            ["tracking.calibrateHint"] = "請自然面向攝影機，放鬆臉部與肩膀。",
            ["tracking.pleaseCalibrate"] = "已偵測到臉部。請面向螢幕放鬆，然後按「校正」設定頭部與身體的零點。",
            ["tracking.calibrated"] = "校正完成。",
            ["tracking.calibrationFailed"] = "校正失敗：期間內偵測不到穩定的臉部，請面向攝影機再試一次。",
            ["tracking.calibrationCleared"] = "已清除校正。",
            ["tracking.calibratedTag"] = "已校正",
            ["tracking.clearCalibration"] = "清除校正",
            ["tracking.mode"] = "模式",
            ["tracking.basic"] = "基本",
            ["tracking.advanced"] = "進階",
            ["tracking.advancedSettings"] = "進階設定",
            ["tracking.mirrorUser"] = "鏡像（像照鏡子）",
            ["tracking.smoothing"] = "平滑",
            ["tracking.headGain"] = "頭部幅度",
            ["tracking.invertPitch"] = "反轉俯仰",
            ["tracking.invertYaw"] = "反轉左右",
            ["tracking.invertRoll"] = "反轉傾斜",
            ["tracking.swapEyes"] = "眼睛左右對調（預設開）",
            ["tracking.noEngine"] = "尚未安裝臉部追蹤引擎。請在專案資料夾執行 Scripts/setup-mediapipe.sh，然後重新開啟 Unity。",
            ["tracking.noModel"] = "找不到臉部追蹤模型。請執行選單 VRMCast › Setup › Rebuild Main Scene。",
            ["tracking.status.off"] = "追蹤已停止",
            ["tracking.status.noEngine"] = "無追蹤引擎",
            ["tracking.status.noModel"] = "缺少模型",
            ["tracking.status.starting"] = "啟動攝影機中…",
            ["tracking.status.searching"] = "尋找臉部中…",
            ["tracking.status.tracking"] = "追蹤中",
            ["tracking.status.cameraError"] = "攝影機問題",
            ["tracking.status.calibrating"] = "校正中",
            ["status.faceOn"] = "臉部：追蹤中",
            ["status.faceSearching"] = "臉部：尋找中",
            ["status.faceOff"] = "臉部：關",
            ["diag.tracking"] = "追蹤：{0} fps · 推論 {1} ms · 遺失 {2}",

            // Lip sync & body
            ["section.lipsync"] = "嘴型同步",
            ["lipsync.mode"] = "來源",
            ["lipsync.camera"] = "攝影機",
            ["lipsync.microphone"] = "麥克風",
            ["lipsync.hybrid"] = "混合",
            ["lipsync.level"] = "音量",
            ["lipsync.sensitivity"] = "靈敏度",
            ["lipsync.gate"] = "噪音門檻",
            ["lipsync.noMicrophone"] = "找不到麥克風",
            ["mic.state.stopped"] = "麥克風未啟動（開始追蹤後啟用）",
            ["mic.state.permission"] = "正在請求麥克風權限…",
            ["mic.state.denied"] = "麥克風權限被拒絕。請到「系統設定 › 隱私權與安全性 › 麥克風」允許 VRMCast。",
            ["mic.state.starting"] = "麥克風啟動中…",
            ["mic.state.running"] = "麥克風運作中。這個麥克風只用來驅動嘴型，與 OBS 的收音無關。",
            ["mic.state.noDevice"] = "找不到所選的麥克風。",
            ["mic.state.failed"] = "麥克風啟動失敗。",
            ["section.body"] = "身體",
            ["body.mode"] = "身體追蹤",
            ["body.off"] = "關閉",
            ["body.upper"] = "上半身",
            ["body.upperArms"] = "上半身＋手臂",
            ["body.upperArmsFingers"] = "上半身＋手臂＋手指",
            ["body.hint"] = "以肩膀與髖部推算軀幹的傾斜、轉向與前傾；手臂依手肘與手腕驅動，離開畫面時自然垂下。手指模式再加上每根手指的彎曲與手腕方向，並以手掌位置反推手臂姿勢；手離開畫面時放鬆張開。校正時一併記錄中立姿勢。",
            ["hands.swap"] = "左右對調（手臂與手指）",
            ["body.invertRoll"] = "身體傾斜反向",
            ["body.invertYaw"] = "身體轉向反向",
            ["body.invertPitch"] = "身體前傾反向",
            ["body.armsFromHands"] = "以手掌位置反算手臂（IK）",
            ["body.wristFromPalm"] = "手腕跟隨手掌方向",
            ["hands.state.off"] = "手指：追蹤未開始。",
            ["hands.state.modeOff"] = "手指：未啟用，請將身體追蹤改為「上半身＋手臂＋手指」。",
            ["hands.state.noEngine"] = "手指：尚未安裝追蹤引擎。",
            ["hands.state.noModel"] = "手指：場景缺少 hand_landmarker 模型，請執行 VRMCast > Setup > Rebuild Main Scene。",
            ["hands.state.starting"] = "手指：手部模型啟動中…",
            ["hands.state.noAvatar"] = "手指：尚未載入模型。",
            ["hands.state.noFingerBones"] = "手指：此 VRM 沒有手指骨骼，無法驅動手指。",
            ["hands.state.searching"] = "手指：{0} fps，尚未看到手掌。請把手舉到胸前、掌心朝鏡頭。（骨骼 {3}）",
            ["hands.state.one"] = "手指：{0} fps，左手彎曲 {1}、右手 {2}（骨骼 {3}）",
            ["hands.state.both"] = "手指：{0} fps，左手彎曲 {1}、右手 {2}（骨骼 {3}）",
            ["diag.hands"] = "手：{0} fps · 推論 {1} ms",
            ["body.noEngine"] = "尚未安裝追蹤引擎，無法使用身體追蹤。",
            ["status.audioOff"] = "音訊：關",
            ["status.audioListening"] = "音訊：聆聽中",
            ["status.audioSpeaking"] = "音訊：說話中",
            ["diag.pose"] = "身體：{0} fps · 推論 {1} ms · 麥克風 {2} dBFS",

            // Profiles, hotkeys, view
            ["profile.manage"] = "管理",
            ["profile.none"] = "（無設定檔）",
            ["profile.title"] = "設定檔",
            ["profile.name"] = "名稱",
            ["profile.new"] = "新增",
            ["profile.save"] = "儲存",
            ["profile.saveAs"] = "另存",
            ["profile.duplicate"] = "複製",
            ["profile.rename"] = "重新命名",
            ["profile.delete"] = "刪除",
            ["profile.autoSave"] = "自動儲存（變更後兩秒）",
            ["profile.relink"] = "重新連結 VRM…",
            ["profile.close"] = "關閉",
            ["profile.hint"] = "設定檔會記住模型、攝影機、麥克風、追蹤模式、校正、嘴型、構圖、背景、輸出與熱鍵。",
            ["profile.missingVrm"] = "找不到設定檔中的模型檔案：{0}。設定檔已保留，請重新連結。",
            ["profile.error.load"] = "無法讀取設定檔。",
            ["profile.error.save"] = "無法儲存設定檔。",
            ["profile.error.delete"] = "無法刪除設定檔。",
            ["section.hotkeys"] = "表情熱鍵",
            ["hotkey.hold"] = "按住",
            ["hotkey.toggle"] = "切換",
            ["hotkey.oneShot"] = "單次",
            ["hotkey.pressKey"] = "按鍵…",
            ["hotkey.hint"] = "點按鍵欄後按下鍵盤設定；Backspace 清除，Esc 取消。輸入文字時熱鍵不會觸發。",
            ["tracking.blinkGain"] = "眨眼幅度",
            ["view.performance"] = "效能模式",
            ["view.standard"] = "顯示控制項",
            ["view.performanceHint"] = "效能模式：控制項已隱藏，輸出照常。按 Tab 或 Esc 返回。",

            // VRM versions
            ["vrm.0x"] = "VRM 0.x",
            ["vrm.10"] = "VRM 1.0",
            ["vrm.unknown"] = "未知版本",

            // Errors (keys referenced from VrmLoadErrors and BackgroundService)
            ["error.noFile"] = "尚未選擇檔案。",
            ["error.fileMissing"] = "找不到檔案，可能已被移動或刪除。",
            ["error.unreadable"] = "無法讀取檔案，請確認你有開啟它的權限。",
            ["error.notVrm"] = "這不是有效的 VRM 檔案。",
            ["error.unsupportedGlb"] = "這個檔案使用了不支援的 glTF 容器版本。",
            ["error.metadata"] = "無法讀取 VRM 中繼資料。",
            ["error.noHumanoid"] = "這個模型沒有相容的人形骨架定義。",
            ["error.springBone"] = "模型已載入，但 SpringBone 資料無效，已停用物理效果。",
            ["error.importer"] = "無法載入模型。檔案可能已損壞，或使用了此版本不支援的功能。",
            ["error.cancelled"] = "已取消載入。",
            ["error.versionMismatch"] = "偵測到此檔案為 {0}，無法以 {1} 載入。",
            ["error.imageMissing"] = "找不到背景圖片。",
            ["error.imageUnreadable"] = "無法讀取背景圖片。",
            ["error.imageFormat"] = "不支援這種圖片格式，請使用 PNG 或 JPEG。",
            ["error.imageLoad"] = "無法載入圖片。",
        };

        public static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Header / status bar
            ["header.subtitle"] = "Render foundation (MVP-A)",
            ["header.profile"] = "Profile: Default",
            ["header.language"] = "Language",
            ["status.face"] = "Face: off",
            ["status.audio"] = "Audio: off",
            ["status.render"] = "Render {0} fps",
            ["status.outputOn"] = "Output: on",
            ["status.outputOff"] = "Output: off",
            ["status.resolution"] = "{0}×{1} | {2} FPS",

            // Model section
            ["section.model"] = "MODEL",
            ["model.none"] = "No avatar loaded",
            ["model.hint"] = "Load a .vrm file to begin.",
            ["model.load"] = "Load VRM",
            ["model.loading"] = "Loading…",
            ["model.unload"] = "Unload",
            ["model.status"] = "{0}{1} · {2} expressions · SpringBone {3}",
            ["model.author"] = " · {0}",
            ["model.springOn"] = "on",
            ["model.springOff"] = "none",
            ["model.loaded"] = "Loaded {0}",
            ["import.title"] = "Advanced import",
            ["import.version"] = "VRM Version",
            ["import.auto"] = "Auto Detect",
            ["import.force0"] = "Force VRM 0.x",
            ["import.force1"] = "Force VRM 1.0",
            ["import.retry"] = "Retry with this version",

            // Framing section
            ["section.framing"] = "FRAMING",
            ["framing.preset"] = "Preset",
            ["framing.face"] = "Face",
            ["framing.bust"] = "Bust",
            ["framing.halfBody"] = "Half Body",
            ["framing.fullBody"] = "Full Body",
            ["framing.zoom"] = "Zoom",
            ["framing.fov"] = "FOV",
            ["framing.resetCamera"] = "Reset Camera",
            ["framing.resetOrientation"] = "Reset Orientation",
            ["framing.reframe"] = "Reframe to Avatar",
            ["framing.hint"] = "Preview: scroll or two-finger swipe = zoom, drag = orbit, right/middle or Shift+drag = pan",

            // Background section
            ["section.background"] = "BACKGROUND",
            ["background.mode"] = "Mode",
            ["background.solid"] = "Solid Color",
            ["background.image"] = "Image",
            ["background.chroma"] = "Chroma Key",
            ["background.transparent"] = "Transparent",
            ["background.keyColor"] = "Key color",
            ["background.color"] = "Color",
            ["background.chooseImage"] = "Choose Image…",
            ["background.clearImage"] = "Clear",
            ["background.noImage"] = "No image selected",
            ["background.fit"] = "Fit",
            ["fit.fill"] = "Fill",
            ["fit.fit"] = "Fit",
            ["fit.stretch"] = "Stretch",
            ["background.colorFormat"] = "Enter a color as #RRGGBB.",

            // Output section
            ["section.output"] = "OUTPUT",
            ["output.quality"] = "Quality",
            ["output.recommended"] = "Recommended",
            ["output.hint"] = "Start Output sends the frame to the virtual camera; without the native component only the debug consumer runs.",
            ["vcam.title"] = "Virtual Camera",
            ["vcam.install"] = "Install / Enable Virtual Camera",
            ["vcam.uninstall"] = "Remove",
            ["vcam.status.unsupported"] = "Status: not supported here ({0})",
            ["vcam.status.unknown"] = "Status: checking…",
            ["vcam.status.notInstalled"] = "Status: not installed",
            ["vcam.status.requesting"] = "Status: asking macOS…",
            ["vcam.status.awaitingApproval"] = "Status: waiting for approval. Allow VRMCast under System Settings › General › Login Items & Extensions › Camera Extensions.",
            ["vcam.status.ready"] = "Status: enabled {0}. OBS can pick \"VRM Live Camera\".",
            ["vcam.status.enabledNoDevice"] = "Status: enabled {0}, but macOS does not list the camera yet. Wait a moment or restart OBS.",
            ["vcam.status.needsReboot"] = "Status: installed; restart macOS to finish.",
            ["vcam.status.failed"] = "Status: failed ({1})",
            ["vcam.status.uninstalling"] = "Status: removing…",
            ["vcam.hint"] = "On first install macOS asks you to allow the extension in System Settings; it stays approved afterwards. Stopping output shows the camera's fallback frame, never a frozen picture.",
            ["vcam.hint.notBundled"] = "This build of the app does not embed the camera extension. Package and sign with Scripts/package-macos.sh first.",
            ["vcam.hint.unsupported"] = "The virtual camera needs macOS and a compiled VRMCastFrameBridge.bundle (Scripts/build-frame-bridge.sh).",
            ["vcam.openFailed"] = "Could not connect to the virtual camera: {0}. Install and approve the extension first.",
            ["vcam.openFailed.generic"] = "Output could not start.",
            ["output.start"] = "Start Output",
            ["output.stop"] = "Stop Output",

            // Diagnostics section
            ["section.diagnostics"] = "DIAGNOSTICS",
            ["diag.render"] = "Render: {0} fps ({1} ms)",
            ["diag.output"] = "Output: {0}×{1} @ {2} · target {3}",
            ["diag.avatar"] = "Avatar: {0} [{1}]",
            ["diag.copy"] = "Copy Diagnostics",
            ["diag.copied"] = "Diagnostics copied to the clipboard.",

            // File picker
            ["picker.loadVrm"] = "Load VRM",
            ["picker.chooseImage"] = "Choose background image",
            ["picker.up"] = "Up",
            ["picker.home"] = "Home",
            ["picker.desktop"] = "Desktop",
            ["picker.downloads"] = "Downloads",
            ["picker.documents"] = "Documents",
            ["picker.cancel"] = "Cancel",
            ["picker.open"] = "Open",
            ["picker.folderUnreadable"] = "This folder cannot be read.",
            ["picker.fileMissing"] = "That file does not exist.",
            ["picker.wrongType"] = "That file type is not supported here.",

            // Camera (webcam)
            ["section.camera"] = "CAMERA",
            ["camera.device"] = "Device",
            ["camera.mirror"] = "Mirror preview",
            ["camera.none"] = "No camera found",
            ["camera.state.stopped"] = "Off (starts with tracking)",
            ["camera.state.permission"] = "Requesting camera permission…",
            ["camera.state.denied"] = "Camera permission denied. Allow VRMCast under System Settings › Privacy & Security › Camera.",
            ["camera.state.starting"] = "Starting…",
            ["camera.state.running"] = "Running",
            ["camera.state.stalled"] = "No frames, trying to recover…",
            ["camera.state.noDevice"] = "The selected camera was not found.",
            ["camera.state.failed"] = "The camera failed to start, retrying…",

            // Tracking
            ["section.tracking"] = "TRACKING",
            ["tracking.start"] = "Start Tracking",
            ["tracking.stop"] = "Stop Tracking",
            ["tracking.calibrate"] = "Calibrate",
            ["tracking.calibrateHint"] = "Look naturally toward the camera. Relax your face and shoulders.",
            ["tracking.pleaseCalibrate"] = "Face detected. Look at the screen naturally, then press Calibrate to set the neutral head and body pose.",
            ["tracking.calibrated"] = "Calibration complete.",
            ["tracking.calibrationFailed"] = "Calibration failed: no steady face was detected. Face the camera and try again.",
            ["tracking.calibrationCleared"] = "Calibration cleared.",
            ["tracking.calibratedTag"] = "calibrated",
            ["tracking.clearCalibration"] = "Clear Calibration",
            ["tracking.mode"] = "Mode",
            ["tracking.basic"] = "Basic",
            ["tracking.advanced"] = "Advanced",
            ["tracking.advancedSettings"] = "Advanced settings",
            ["tracking.mirrorUser"] = "Mirror (like a mirror)",
            ["tracking.smoothing"] = "Smoothing",
            ["tracking.headGain"] = "Head gain",
            ["tracking.invertPitch"] = "Invert pitch",
            ["tracking.invertYaw"] = "Invert yaw",
            ["tracking.invertRoll"] = "Invert roll",
            ["tracking.swapEyes"] = "Swap eye sides (default on)",
            ["tracking.noEngine"] = "The face tracking engine is not installed. Run Scripts/setup-mediapipe.sh in the project folder, then reopen Unity.",
            ["tracking.noModel"] = "The face tracking model is missing. Run VRMCast › Setup › Rebuild Main Scene.",
            ["tracking.status.off"] = "Tracking off",
            ["tracking.status.noEngine"] = "No tracking engine",
            ["tracking.status.noModel"] = "Model missing",
            ["tracking.status.starting"] = "Starting camera…",
            ["tracking.status.searching"] = "Looking for a face…",
            ["tracking.status.tracking"] = "Tracking",
            ["tracking.status.cameraError"] = "Camera problem",
            ["tracking.status.calibrating"] = "Calibrating",
            ["status.faceOn"] = "Face: tracking",
            ["status.faceSearching"] = "Face: searching",
            ["status.faceOff"] = "Face: off",
            ["diag.tracking"] = "Tracking: {0} fps · inference {1} ms · dropped {2}",

            // Lip sync & body
            ["section.lipsync"] = "LIP SYNC",
            ["lipsync.mode"] = "Source",
            ["lipsync.camera"] = "Camera",
            ["lipsync.microphone"] = "Microphone",
            ["lipsync.hybrid"] = "Hybrid",
            ["lipsync.level"] = "Level",
            ["lipsync.sensitivity"] = "Sensitivity",
            ["lipsync.gate"] = "Noise gate",
            ["lipsync.noMicrophone"] = "No microphone found",
            ["mic.state.stopped"] = "Microphone off (starts with tracking)",
            ["mic.state.permission"] = "Requesting microphone permission…",
            ["mic.state.denied"] = "Microphone permission denied. Allow VRMCast under System Settings › Privacy & Security › Microphone.",
            ["mic.state.starting"] = "Starting microphone…",
            ["mic.state.running"] = "Microphone running. It only drives the mouth; OBS keeps its own audio.",
            ["mic.state.noDevice"] = "The selected microphone was not found.",
            ["mic.state.failed"] = "The microphone failed to start.",
            ["section.body"] = "BODY",
            ["body.mode"] = "Body tracking",
            ["body.off"] = "Off",
            ["body.upper"] = "Upper Body",
            ["body.upperArms"] = "Upper Body + Arms",
            ["body.upperArmsFingers"] = "Upper Body + Arms + Fingers",
            ["body.hint"] = "Torso tilt, turn and lean from shoulders and hips; arms follow elbows and wrists and rest when out of frame. The fingers mode adds per-finger curl and wrist orientation and solves the arm from the palm position; hands relax open when out of frame. Calibrate also stores the neutral posture.",
            ["hands.swap"] = "Swap left and right (arms and fingers)",
            ["body.invertRoll"] = "Invert body tilt",
            ["body.invertYaw"] = "Invert body turn",
            ["body.invertPitch"] = "Invert body lean",
            ["body.armsFromHands"] = "Solve arms from the palm position (IK)",
            ["body.wristFromPalm"] = "Wrists follow the palm orientation",
            ["hands.state.off"] = "Fingers: tracking is off.",
            ["hands.state.modeOff"] = "Fingers: off. Set body tracking to \"Upper Body + Arms + Fingers\".",
            ["hands.state.noEngine"] = "Fingers: the tracking engine is not installed.",
            ["hands.state.noModel"] = "Fingers: the scene lacks the hand_landmarker model. Run VRMCast > Setup > Rebuild Main Scene.",
            ["hands.state.starting"] = "Fingers: starting the hand model…",
            ["hands.state.noAvatar"] = "Fingers: no avatar loaded.",
            ["hands.state.noFingerBones"] = "Fingers: this VRM has no finger bones.",
            ["hands.state.searching"] = "Fingers: {0} fps, no hand seen yet. Raise a hand to chest height, palm to the camera. (bones {3})",
            ["hands.state.one"] = "Fingers: {0} fps, left curl {1}, right {2} (bones {3})",
            ["hands.state.both"] = "Fingers: {0} fps, left curl {1}, right {2} (bones {3})",
            ["diag.hands"] = "Hands: {0} fps · inference {1} ms",
            ["body.noEngine"] = "Body tracking needs the tracking engine to be installed.",
            ["status.audioOff"] = "Audio: off",
            ["status.audioListening"] = "Audio: listening",
            ["status.audioSpeaking"] = "Audio: speaking",
            ["diag.pose"] = "Body: {0} fps · inference {1} ms · mic {2} dBFS",

            // Profiles, hotkeys, view
            ["profile.manage"] = "Manage",
            ["profile.none"] = "(no profiles)",
            ["profile.title"] = "Profiles",
            ["profile.name"] = "Name",
            ["profile.new"] = "New",
            ["profile.save"] = "Save",
            ["profile.saveAs"] = "Save As",
            ["profile.duplicate"] = "Duplicate",
            ["profile.rename"] = "Rename",
            ["profile.delete"] = "Delete",
            ["profile.autoSave"] = "Auto-save (two seconds after a change)",
            ["profile.relink"] = "Relink VRM…",
            ["profile.close"] = "Close",
            ["profile.hint"] = "A profile remembers the avatar, camera, microphone, tracking mode, calibration, lip sync, framing, background, output and hotkeys.",
            ["profile.missingVrm"] = "The profile's avatar file is missing: {0}. The profile is kept; relink the file.",
            ["profile.error.load"] = "The profile could not be read.",
            ["profile.error.save"] = "The profile could not be saved.",
            ["profile.error.delete"] = "The profile could not be deleted.",
            ["section.hotkeys"] = "EXPRESSION HOTKEYS",
            ["hotkey.hold"] = "Hold",
            ["hotkey.toggle"] = "Toggle",
            ["hotkey.oneShot"] = "One Shot",
            ["hotkey.pressKey"] = "Press…",
            ["hotkey.hint"] = "Click a key cell, then press a key; Backspace clears, Esc cancels. Hotkeys are ignored while typing.",
            ["tracking.blinkGain"] = "Blink strength",
            ["view.performance"] = "Performance Mode",
            ["view.standard"] = "Show Controls",
            ["view.performanceHint"] = "Performance mode: controls hidden, output continues. Press Tab or Esc to return.",

            // VRM versions
            ["vrm.0x"] = "VRM 0.x",
            ["vrm.10"] = "VRM 1.0",
            ["vrm.unknown"] = "Unknown",

            // Errors
            ["error.noFile"] = "No file was selected.",
            ["error.fileMissing"] = "The file could not be found. It may have been moved or deleted.",
            ["error.unreadable"] = "The file could not be read. Check that you have permission to open it.",
            ["error.notVrm"] = "This file is not a valid VRM file.",
            ["error.unsupportedGlb"] = "This file uses an unsupported glTF container version.",
            ["error.metadata"] = "VRM metadata could not be read.",
            ["error.noHumanoid"] = "The avatar has no compatible humanoid definition.",
            ["error.springBone"] = "The model loaded, but SpringBone data is invalid. Physics has been disabled.",
            ["error.importer"] = "The avatar could not be loaded. The file may be damaged or use features this version does not support.",
            ["error.cancelled"] = "Loading was cancelled.",
            ["error.versionMismatch"] = "This file was detected as {0}; loading it as {1} is not supported.",
            ["error.imageMissing"] = "The background image could not be found.",
            ["error.imageUnreadable"] = "The background image could not be read.",
            ["error.imageFormat"] = "The image format is not supported. Use PNG or JPEG.",
            ["error.imageLoad"] = "The image could not be loaded.",
        };
    }
}
